services:
  postgres:
    image: postgres:15
    container_name: pc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pc_blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./pc-backend
    container_name: pc_backend
    ports:
      - "5050:5050"
    environment:
      - DOCKER_ENV=true
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pc_blog
      - DB_HOST=pc_postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pc_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
  
